[package]
name = "calculate_rust"
version = "0.1.0"
edition = "2021"
authors = ["haruki7049 <tontonkirikiri@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
